#!/usr/bin/env python3

import requests
from bs4 import BeautifulSoup
from PIL import Image
import json
import re

class Weibo:

    "The class is used to look for the specified keyword and repost the relative post"

    def __init__(self, username, password):
        self.username = username
        self.password = password
        self.session = requests.session()

    def login(self):

        "login on to weibo with the provided username and password, return response and session"

        to_login_response = self.session.get('http://login.weibo.cn/login/?ns=1&revalid=2&backURL=http%3A%2F%2Fweibo.cn%2F&backTitle=%CE%A2%B2%A9&vt=').content
        soup = BeautifulSoup(to_login_response, 'html.parser')

        # get vk, which seems to be a random number generated by server
        vk_value = soup.find('input', attrs={'name' : 'vk'}).get('value')

        # get the name of the password
        password_name = soup.find('input', attrs={'type' : 'password'}).get('name')


        # post username and password to server
        data = {'mobile': self.username, password_name: self.password, 'remember': 'on', 'backURL': 'http://weibo.cn/', 'backTitle': '微博', 'vk': vk_value, 'submit': '登录'}
        login_response = self.session.post('http://login.weibo.cn/login/?rand=1891396374&backURL=http%3A%2F%2Fweibo.cn%2F&backTitle=%E5%BE%AE%E5%8D%9A&vt=4&revalid=2&ns=1', data)

        soup = BeautifulSoup(login_response.content, 'html.parser')
        if '请输入验证码' in login_response.content.decode('utf8'):
            # OK, sina found that something weird happened, we have to input the captcha
            captcha_address = soup.find('img').get('src')
            capId = soup.find('input', attrs = {'name': 'capId'}).get('value')
            captcha_image = requests.get(captcha_address)
            with open('/tmp/captcha', 'wb') as f:
                f.write(captcha_image.content)
            img = Image.open('/tmp/captcha')
            img.show()
            
            # Let the user input the captcha
            captcha = input('Please input the captcha: ')
            data['capId'] = capId
            data['code'] = captcha

            # Let's try to log in again, we should succeed this time
            login_response = self.session.post('http://login.weibo.cn/login/?rand=1891396374&backURL=http%3A%2F%2Fweibo.cn%2F&backTitle=%E5%BE%AE%E5%8D%9A&vt=4&revalid=2&ns=1', data)

        return login_response

    def _print_response_page(self, response, path):
        with open(path, 'w') as f:
            f.write(response.content.decode('utf8'))

if __name__ == '__main__':
    weibo = Weibo('username', 'password')
    login_response = weibo.login()
    
    # You can refer to /tmp/login.html to check if login is successful or not.
    weibo._print_response_page(login_response, '/tmp/login.html')
